apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "workload.fullname" . }}-queryparams
spec:
  parentRefs:
    - name: eg
      namespace: default
  hostnames:
    - "{{ .Values.app.name }}.saya.local"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "workload.fullname" . }}
          port: {{ .Values.service.port }}
      matches:
        - queryParams:
            type: Exact
            name: x-katana-version
            value: {{ .Values.workload.version }}

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "workload.fullname" . }}-headers
spec:
  parentRefs:
    - name: eg
      namespace: default
  hostnames:
    - "{{ .Values.app.name }}.saya.local"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "workload.fullname" . }}
          port: {{ .Values.service.port }}
      matches:
        - headers:
            type: Exact
            name: x-katana-version
            value: {{ .Values.workload.version }}
