apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "workload.fullname" . }}
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "{{ .Values.app.name }}.saya.local"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "workload.fullname" . }}
          port: {{ .Values.service.port }}
          weight: {{ .Values.workload.weight }}
      matches:
        - path:
            type: PathPrefix
            value: /
