apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "{{ .Values.app.name }}.saya.local"
  rules:
    - backendRefs:
        - kind: Service
          name: {{ include "workload.fullname" . }}
          port: 80
          weight: 0
      matches:
        - path:
            type: PathPrefix
            value: /
