apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment.name }}
spec:
  parentRefs:
    - name: eg
      namespace: default
  hostnames:
    - "{{ .Values.app.name }}.saya.local"
  rules:
    - backendRefs:
        {{ if .Values.environment.artifacts }}
        {{- range .Values.environment.artifacts }}
        - group: ""
          kind: Service
          name: "{{ .name }}-{{ .id }}-workload"
          port: {{ $.Values.service.port }}
          weight: {{ .weight }}
        {{- end }}
        {{- else }}
        []
        {{- end }}
