apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment.name }}-trafficpolicy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ .Values.app.name }}-{{ .Values.environment.name }}
  loadBalancer:
    type: RoundRobin
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment.name }}
spec:
  parentRefs:
    - name: eg
      namespace: default
  hostnames:
    - "{{ .Values.app.name }}.saya.local"
  rules:
    - backendRefs:
        {{ if .Values.artifacts }}
        {{- range .Values.artifacts }}
        - group: ""
          kind: Service
          name: "{{ $.Values.app.name }}-{{ $.Values.environment.name }}-{{ .id }}"
          port: {{ $.Values.service.port }}
          weight: {{ default .weight 0 }}
        {{- end }}
        {{- else -}}
        []
        {{- end }}
